blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://stackoverflow.com/questions/tagged/spring-boot
    about: Please ask questions on Gitter or StackOverflow.
  - name: Security Vulnerability
    url: https://pivotal.io/security
    about: Please don't raise security vulnerabilities here.